In [1]:
import numpy as np
from models.classifiers import Adaline
import matplotlib.pyplot as plt 
from sklearn.preprocessing import MinMaxScaler, StandardScaler

In [20]:
X = np.random.randint(1000, size=(5, 2))
X

array([[591, 889],
       [717, 367],
       [560, 801],
       [341, 766],
       [ 49, 641]])

In [21]:
Y = (X * 2).sum(axis=1)
Y

array([2960, 2168, 2722, 2214, 1380])

In [23]:
scaler = MinMaxScaler()
X = scaler.fit_transform(X)
X

array([[0.81137725, 1.        ],
       [1.        , 0.        ],
       [0.76497006, 0.83141762],
       [0.43712575, 0.76436782],
       [0.        , 0.52490421]])

In [30]:
model = Adaline(eta=0.01, n_iter=100000, mse_th=0.05)
model.fit(X, Y)
model.mse_

0.04973679721253921

In [9]:
model = Adaline(eta=0.0001, n_iter=50)
model.fit(X, Y)
model.mse_

24.5388360827805

In [10]:
model = Adaline(eta=0.001, n_iter=1000)
model.fit(X, Y)
model.mse_

9.81960809333335e-20

In [11]:
model = Adaline(eta=0.0001, n_iter=1000)
model.fit(X, Y)
model.mse_

0.02625768028984657

In [12]:
X = np.random.randint(1000, size=(5, 2))
X

array([[288, 417],
       [419, 544],
       [987, 196],
       [ 45, 809],
       [145, 270]])

In [13]:
Y = (X * 2).sum(axis=1)
Y

array([1410, 1926, 2366, 1708,  830])

In [14]:
model = Adaline(eta=0.0001, n_iter=1000)
model.fit(X, Y)
model.mse_

/home/ms47/Documents/programming/project/neural_network_tasts/src/models/classifiers/adaline.py:27: RuntimeWarning: overflow encountered in square
  self.mse_ = (errors ** 2).sum() / X.shape[0]
/home/ms47/Documents/programming/project/neural_network_tasts/src/models/classifiers/adaline.py:24: RuntimeWarning: invalid value encountered in add
  self.w_ += self.eta * X.T.dot(errors)


nan

In [15]:
scaler = MinMaxScaler()
X = scaler.fit_transform(X)
X

array([[0.25796178, 0.36052202],
       [0.3970276 , 0.56769984],
       [1.        , 0.        ],
       [0.        , 1.        ],
       [0.10615711, 0.12071778]])

In [17]:
model = Adaline(eta=0.0001, n_iter=1000)
model.fit(X, Y)
model.mse_

2148837.106869414

In [29]:
np.ones(3)

array([1., 1., 1.])

In [10]:
x = np.array([1, 2, 3])
w = np.array([1, 2, 3])
np.dot(x, w)

14